# Generated by Django 4.1.2 on 2022-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
